site_name: OhMyAdmin
site_description: "Backoffice and admin generator for Starlette."
repo_url: https://github.com/alex-oleshkevich/ohmyadmin
site_url: http://localhost:8002
repo_name: "alex-oleshkevich/ohmyadmin"
site_dir: "site"
nav:
    - Introduction: 'index.md'
    - Demo: 'demo.md'
    - Pages:
        "Simple pages": pages/index.md
    - API:
        "Simple page": api/simple_page_api.md
theme:
    name: "material"
    logo: logo.svg
    palette:
        -   scheme: 'default'
            media: '(prefers-color-scheme: light)'
            toggle:
            icon: 'material/lightbulb'
            name: "Switch to dark mode"
        -   scheme: 'slate'
            media: '(prefers-color-scheme: dark)'
            primary: 'blue'
            toggle:
            icon: 'material/lightbulb-outline'
            name: 'Switch to light mode'
    features:
        - content.code.copy
    icon:
    repo: fontawesome/brands/github

markdown_extensions:
    - mkautodoc
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.keys
    - pymdownx.mark


plugins:
    - search
    - mkdocstrings
