# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
    push:
    release:
        types: [ created ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'
                    cache: 'pip'

            -   uses: actions/setup-node@v4
                with:
                    node-version: v21
                    cache: 'npm'
                    registry-url: https://registry.npmjs.org/

            -   name: Install javascript dependencies
                run: yarn install
                working-directory: assets

            -   name: Build assets
                run: npm run build

            -   name: Install python dependencies
                run: |
                    python -m pip install --upgrade pip poetry
                    poetry config virtualenvs.create false
                    poetry install --no-interaction --only main

            -   name: Build package
                run: |
                    poetry config pypi-token.pypi "{{ secrets.PYPI_TOKEN }}"
                    poetry build
                    poetry publish

            -   name: Archive build artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: ohmyadmin.zip
                    retention-days: 7
                    path: |
                        dist
